  
  name: Update Equity Data
  
  on:
    schedule:
    - cron: '34 10 * * *'
    workflow_dispatch:
  
  jobs:
    update-data:
      runs-on: ubuntu-latest
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_REGION: ${{ vars.GCP_REGION }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        QUANDL_API_KEY: ${{ secrets.QUANDL_API_KEY }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      steps:
        - uses: actions/checkout@v4
  
        - name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v2
          with:
            credentials_json: ${{ env.GCP_SA_KEY }}
  
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'
  
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
  
        - name: Run data refresh
          env:
            DATABASE_URL: ${{ env.DATABASE_URL }}
            QUANDL_API_KEY: ${{ env.QUANDL_API_KEY }}
            GCP_PROJECT_ID: ${{ env.GCP_PROJECT_ID }}
          run: |
            python -m data_pipeline.update_financial_data --years 10
