name: Update Equity Data

on:
  schedule:
    - cron: '34 10 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ vars.GCP_REGION }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      QUANDL_API_KEY: ${{ secrets.QUANDL_API_KEY }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      CLIENT_SECRET_JSON: ${{ secrets.CLIENT_SECRET_JSON }}
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}

      - name: Create or update Gmail client secret in Secret Manager
        run: |
          echo "$CLIENT_SECRET_JSON" | gcloud secrets create GMAIL_CLIENT_SECRET --data-file=- || gcloud secrets versions add GMAIL_CLIENT_SECRET --data-file=-

      - name: Debug Environment Variables
        run: |
          echo "GCP_PROJECT_ID=${{ env.GCP_PROJECT_ID }}"
          echo "DATABASE_URL=${{ env.DATABASE_URL }}"
          echo "QUANDL_API_KEY=${{ env.QUANDL_API_KEY }}"
          echo "GCP_REGION=${{ env.GCP_REGION }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data refresh
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
          QUANDL_API_KEY: ${{ env.QUANDL_API_KEY }}
          GCP_PROJECT_ID: ${{ env.GCP_PROJECT_ID }}
          GMAIL_CREDENTIALS_SECRET_NAME: GMAIL_CLIENT_SECRET
        run: |
          python -m data_pipeline.update_financial_data --years 10
