name: Update Equity data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Verify environment variables
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          QUANDL_API_KEY: ${{ secrets.QUANDL_API_KEY }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          missing=()
          for var in DATABASE_URL QUANDL_API_KEY GCP_PROJECT_ID GCP_SA_KEY; do
            if [ -z "${!var}" ]; then
              missing+=("$var")
            fi
          done
          if [ ${#missing[@]} -ne 0 ]; then
            echo "Missing required environment variables: ${missing[*]}"
            exit 1
          fi
      - name: Run data refresh
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          QUANDL_API_KEY: ${{ secrets.QUANDL_API_KEY }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          python data_pipeline/update_financial_data.py --years 10
