# Copy this file to .streamlit/secrets.toml and update with your own values
# Example Streamlit secrets configuration

# Database connection string
DATABASE_URL = "postgresql://user:password@host:5432/database"

# API keys
QUANDL_API_KEY = "your-quandl-api-key"
